[project]
name = "docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sphinx>=9.0.4",
    "sphinx-autobuild>=2025.8.25",
    "sphinxcontrib-mermaid>=1.2.3",
]
